apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jyehwto0g-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jyehwto0g-java-springboot-gitops